name: test_f2py_2021            # default is root
channels:
- conda-forge
- bioconda
dependencies:         # everything under this, installed by conda
- numpy
- scipy
- netcdf4
- pytest
- matplotlib=2.2.2
- ecmwfapi
- cartopy
- earthengine-api
# The packages below are optional, for downloading ERA5
- pip
- lxml
- pandas
- pip:
    - cdsapi